- name: Update Nezha README
  run: python nezha_readme_status.py
  env:
    NEZHA_URL: ${{ secrets.NEZHA_URL }}
    NEZHA_USERNAME: ${{ secrets.NEZHA_USERNAME }}
    NEZHA_PASSWORD: ${{ secrets.NEZHA_PASSWORD }}
